/aw/planning/aw_planning/itinerary/park_id : !!str jiading
/aw/planning/aw_planning/itinerary/route_id : !!str 7 
/aw/planning/aw_planning/itinerary/tasks :
#- task_type :   !!str script
#  script_name:  !!str script/start/check_key.py jiading_test

- task_type :   !!str script
  script_name:  !!str $(rospack find aw_vehicle)/script/yutong/wash_switch.py

# close map: s61 - s42
- task_type :   !!str map
  start_east :    !!float 331573.57500 
  start_north:    !!float 3467754.02500
  end_east :    !!float 331618.67500
  end_north:    !!float 3467089.35000
  stop_check :  !!bool true 
  max_velo  :   !!float 1.2
  execute_mode: !!int 2
  use_rel_ref:  !!bool true
  terminal_dist : !!float 5.0

- task_type :   !!str script
  script_name:  !!str $(rospack find aw_vehicle)/script/yutong/wash_switch.py

# middle map: s44 - s62
- task_type :   !!str map
  start_east :    !!float 331707.15000
  start_north:    !!float 3467110.00000
  end_east :    !!float 331585.37500
  end_north:    !!float 3467741.95000
  stop_check :  !!bool true 
  max_velo  :   !!float 3.0
  execute_mode: !!int 2
  use_rel_ref:  !!bool false
  terminal_dist : !!float 40.0

/aw/planning/aw_planning/itinerary/task_index : !!int 0
/aw/planning/aw_planning/itinerary/repeated : !!bool false
