/aw/planning/aw_planning/itinerary/park_id : !!str jiading
/aw/planning/aw_planning/itinerary/route_id : !!str 2
/aw/planning/aw_planning/itinerary/tasks :
  #- task_type :   !!str script
  #  script_name:  !!str script/start/check_key.py jiading_test
  #- task_type :   !!str script
  #  script_name:  !!str $(rospack find aw_vehicle)/script/yutong/wash_switch.py
# start section: s1 - s99
# section: s61 - s101, close
  - task_type :   !!str map
    start_east :    !!float 331573.27500 
    start_north:    !!float 3467753.82500
    end_east :    !!float 331921.17500
    end_north:    !!float 3467140.62500
    stop_check :  !!bool true
    max_velo  :   !!float 1.5
    execute_mode: !!int 2
    use_rel_ref:  !!bool true
    terminal_dist : !!float 40.0
#  - task_type :   !!str script
#    script_name:  !!str $(rospack find aw_vehicle)/script/yutong/wash_switch.py
/aw/planning/aw_planning/itinerary/task_index : !!int 0
/aw/planning/aw_planning/itinerary/repeated : !!bool true
