/aw/planning/aw_planning/itinerary/park_id : !!str beijing_chaoyang
/aw/planning/aw_planning/itinerary/route_id : !!str 5
/aw/planning/aw_planning/itinerary/tasks :
  - task_type :   !!str script
    script_name:  !!str script/start/check_key.py chaoyang_park_start
  - task_type :   !!str map
    start_east :    !!float 455180.10833
    start_north:    !!float 4422583.58611
    end_east :    !!float 455179.4833
    end_north:    !!float 4422614.23611
    stop_check :  !!bool false
    max_velo  :   !!float 0.5
    execute_mode: !!int 2
    use_rel_ref:  !!bool false
  - task_type :   !!str script
    script_name:  !!str $(rospack find aw_vehicle)/script/jingda/wash_on_dry.py
# the first part going cross the brige
  - task_type :   !!str map
    start_east :    !!float 455180.10833
    start_north:    !!float 4422583.58611
    end_east :    !!float 455376.15000
    end_north:    !!float 4422670.67500
    stop_check :  !!bool false
    execute_mode: !!int 2
    use_rel_ref:  !!bool false
# the north part going east, update the end point
  - task_type :   !!str map
    start_east :    !!float 455180.10833
    start_north:    !!float 4422583.58611
#    end_east :    !!float 455581.5
#    end_north:    !!float 4422809.575
    end_east :    !!float 455586.32500
    end_north:    !!float 4422804.07500
    stop_check :  !!bool false
    execute_mode: !!int 2
    use_rel_ref:  !!bool true
  - task_type :   !!str map
    start_east :    !!float 455180.10833
    start_north:    !!float 4422583.58611
    end_east :    !!float 455591.6
    end_north:    !!float 4422797.875
    stop_check :  !!bool true
    execute_mode: !!int 2
    use_rel_ref:  !!bool false 
  - task_type :   !!str script
    script_name:  !!str $(rospack find aw_vehicle)/script/jingda/wash_off.py
# point to new point
  - task_type :   !!str point_to
    end_east :    !!float 455579.3
    end_north:    !!float 4422816.075
    max_velo  :   !!float 0.5
    lateral_safe: !!float 0.0
  - task_type :   !!str script
    script_name:  !!str $(rospack find aw_vehicle)/script/jingda/wash_on_dry.py
# map, back, use_rel_ref = false
  - task_type :   !!str map
    start_east :    !!float 455208.95208
    start_north:    !!float 4422642.49445
    end_east :    !!float 455584.95
    end_north:    !!float 4422811.025
    stop_check :  !!bool false
    execute_mode: !!int 2
    use_rel_ref:  !!bool false
#the rest of the outer part
  - task_type :   !!str map
    start_east :    !!float 455208.95208
    start_north:    !!float 4422642.49445
    end_east :    !!float 455564.27500
    end_north:    !!float 4422833.67500
    stop_check :  !!bool false
    execute_mode: !!int 2
    use_rel_ref:  !!bool true
#the last part of outer part
  - task_type :   !!str map
    start_east :  !!float 455352.65208
    start_north:  !!float 4422631.79445
    end_east :    !!float 455374.47500
    end_north:    !!float 4422672.12500
    stop_check :  !!bool false
    execute_mode: !!int 2
#    use_rel_ref:  !!bool false
#    center_type:   !!int 0
##    center_offset: !!float -0.3
    use_rel_ref:  !!bool true
  - task_type :   !!str map
    start_east :  !!float 455352.65208
    start_north:  !!float 4422631.79445
    end_east :    !!float 455194.50000
    end_north:    !!float 4422631.62500
    stop_check :  !!bool true
    execute_mode: !!int 2
    use_rel_ref:  !!bool false
  - task_type :   !!str script
    script_name:  !!str $(rospack find aw_vehicle)/script/jingda/wash_off.py
  - task_type :   !!str map
    start_east :  !!float 455352.65208
    start_north:  !!float 4422631.79445
    end_east :    !!float 455183.67500
    end_north:    !!float 4422599.22500
    stop_check :  !!bool true
    max_velo :    !!float 0.5
    execute_mode: !!int 2
    use_rel_ref:  !!bool false
  - task_type :   !!str parking
# pose from localized
#     end_east :    !!float 455179.142669
#     end_north :   !!float 4422584.89025
#     end_yaw :     !!float 1.9191982045404146
# pose from map
    end_east :    !!float 455180.10833
    end_north :   !!float 4422583.58611
    end_yaw :     !!float 1.91
    max_velo :    !!float 0.5
   #-  task_type :   !!str script
   #   script_name:  !!str script/start/stop_key.py chaoyang_park_start


/aw/planning/aw_planning/itinerary/task_index : !!int 0
/aw/planning/aw_planning/itinerary/repeated : !!bool false
