/aw/planning/aw_planning/itinerary/park_id : !!str shanghai_keyuan
/aw/planning/aw_planning/itinerary/route_id : !!str 4
/aw/planning/aw_planning/itinerary/tasks :
   - task_type :   !!str script
     script_name:  !!str script/start/check.py
   - task_type :   !!str script
     script_name:  !!str /home/autowise/autowise/ros/vehicle/aw_vehicle/script/yutong/blink.py
#  start_point and then turn around
   - task_type :   !!str map
     start_east :  !!float 366736.60
     start_north:  !!float 3448540.37
     end_east :    !!float 366709.175
     end_north:    !!float 3448542.65
     stop_check :  !!bool true
     execute_mode: !!int 2
     use_rel_ref:  !!bool false
   - task_type :   !!str script
     script_name:  !!str /home/autowise/autowise/ros/vehicle/aw_vehicle/script/yutong/wash_switch.py
#  wash the north part
   - task_type :   !!str map
     start_east :  !!float 366726.49
     start_north:  !!float 3448541.15
     end_east :    !!float 366330.25
     end_north:    !!float 3448736.25
     stop_check :  !!bool false
     execute_mode: !!int 2
     use_rel_ref:  !!bool true
   - task_type :   !!str map
     start_east :  !!float 366726.49
     start_north:  !!float 3448541.15
     end_east :    !!float 366309.046025
     end_north:    !!float 3448750.56565
     stop_check :  !!bool true
     execute_mode: !!int 2
     use_rel_ref:  !!bool false
   - task_type :   !!str script
     script_name:  !!str /home/autowise/autowise/ros/vehicle/aw_vehicle/script/yutong/wash_switch.py
#  turn around
   - task_type :   !!str parking
     end_east : !!float 366290.90
     end_north: !!float 3448750.62
     end_yaw :     !!float -2.26
     max_velo :  !!float 1.0
     stop_secs : !!float 10.0
     terminal_dist : !!float 0.5
     terminal_diff_yaw : !!float 0.3
     accuracy_stop : !!bool true
   - task_type :   !!str parking
     end_east :  !!float 366294.44106333825
     end_north:  !!float 3448757.584861618
     end_yaw :     !!float -1.8
     max_velo :  !!float 0.5
     stop_secs : !!float 2.0
     terminal_dist : !!float 1.0
     terminal_diff_yaw : !!float 0.3
   - task_type :   !!str parking
     end_east :  !!float 366303.075
     end_north:  !!float 3448740.55
     end_yaw :     !!float -0.58
     max_velo :  !!float 1.0
     stop_secs : !!float 2.0
     terminal_dist : !!float 1.0
     terminal_diff_yaw : !!float 0.3
   - task_type :   !!str script
     script_name:  !!str /home/autowise/autowise/ros/vehicle/aw_vehicle/script/yutong/wash_switch.py
# wash the south part
   - task_type :   !!str map
     start_east :  !!float 366293.175
     start_north:  !!float 3448747.825
     end_east :    !!float 366863.73
     end_north:    !!float 3448519.16
     stop_check :  !!bool true
     execute_mode: !!int 2
     use_rel_ref:  !!bool true
   - task_type :   !!str script
     script_name:  !!str /home/autowise/autowise/ros/vehicle/aw_vehicle/script/yutong/wash_switch.py
# turn around
   - task_type :   !!str map
     start_east :    !!float 366860.85
     start_north:    !!float 3448519.65
     end_east :    !!float 366867.8
     end_north:    !!float 3448535.25
     stop_check :  !!bool true
     execute_mode: !!int 2
     use_rel_ref:  !!bool false
   - task_type :   !!str script
     script_name:  !!str /home/autowise/autowise/ros/vehicle/aw_vehicle/script/yutong/wash_switch.py
#  wash the north part
   - task_type :   !!str map
     start_east :  !!float 366876.8
     start_north:  !!float 3448535.25
     end_east :    !!float 366750.56
     end_north:    !!float 3448542.01
     stop_check :  !!bool false
     execute_mode: !!int 2
     use_rel_ref:  !!bool true
   - task_type :   !!str map
     start_east :    !!float 366783.18
     start_north:    !!float 3448541.976
     end_east :    !!float 366730.65
     end_north:    !!float 3448543.30
     stop_check :  !!bool true
     execute_mode: !!int 2
     use_rel_ref:  !!bool false
     center_type:   !!int 0
     center_offset: !!float  -2.0
     rel_border_dis: !!float 0.0
     rel_point_x:   !!float 0.0
     rel_point_y:   !!float 0.0
   - task_type :   !!str script
     script_name:  !!str /home/autowise/autowise/ros/vehicle/aw_vehicle/script/yutong/wash_switch.py
#  to the trash dumping pose
   - task_type :   !!str parking
     end_east :    !!float 366710.90
     end_north :   !!float 3448546.51
     end_yaw :     !!float 2.47332032795
   - task_type :   !!str parking
#     end_east :    !!float 366725.38148
#     end_north:    !!float 3448526.96282
#     end_yaw :     !!float 1.53429084529
     end_east :    !!float 366725.855017
     end_north:    !!float 3448526.91266
     end_yaw :     !!float 1.49693376025
     max_velo:  !!float 0.5
     terminal_dist : !!float 0.5
     accuracy_stop : !!bool true
     check_free_dist : !!float 8.0
#  dump on
   - task_type :   !!str script
     script_name:  !!str ../../vehicle/aw_vehicle/script/yutong/dump_on.py
   - task_type :   !!str script
     script_name:  !!str sleep 5
#  dump off
   - task_type :   !!str script
     script_name:  !!str ../../vehicle/aw_vehicle/script/yutong/dump_off.py
#  to the final parking pose
   - task_type :   !!str parking
     end_east :    !!float 366710.90
     end_north :   !!float 3448546.51
     end_yaw :     !!float 2.47332032795
   - task_type :   !!str parking
     end_east :    !!float 366734.0
     end_north:    !!float 3448540.37
     end_yaw :     !!float 3.05727523835
     max_velo:  !!float 0.5
   - task_type :   !!str script
     script_name:  !!str /home/autowise/autowise/ros/vehicle/aw_vehicle/script/yutong/blink.py

/aw/planning/aw_planning/itinerary/task_index : !!int 8
#parking index 16
#/aw/planning/aw_planning/itinerary/task_index : !!int 16
/aw/planning/aw_planning/itinerary/repeated : !!bool false

