#!/bin/bash
day=$1
mysql -uaw_monitor -hszjjh-webserver.szjjh.autowise.ai -p123Qwe aw_monitor_system -e "select week(begin_timestamp,1),sum(timestampdiff(MINUTE,begin_timestamp,end_timestamp))/60 as beijing_duration, count(distinct(vehicle_id))  ,count(distinct(date_format(begin_timestamp,'%Y%m%d'))) from  task_execution  where begin_timestamp>'$day' and park_id in ('beijing_huanbao_park','beijing_haidian_jiaxiao') group by year(begin_timestamp),week(begin_timestamp,1);"|python avg.py > a
mysql -uaw_monitor -hszjjh-webserver.szjjh.autowise.ai -p123Qwe aw_monitor_system -e "select week(begin_timestamp,1),sum(timestampdiff(MINUTE,begin_timestamp,end_timestamp))/60 as disney_duration, count(distinct(vehicle_id))   ,count(distinct(date_format(begin_timestamp,'%Y%m%d'))) from  task_execution  where begin_timestamp>'$day' and park_id in ('shanghai_disney') group by year(begin_timestamp),week(begin_timestamp,1);"|python avg.py > b
mysql -uaw_monitor -hszjjh-webserver.szjjh.autowise.ai -p123Qwe aw_monitor_system -e "select week(begin_timestamp,1),sum(timestampdiff(MINUTE,begin_timestamp,end_timestamp))/60 as auto_duration, count(distinct(vehicle_id))   ,count(distinct(date_format(begin_timestamp,'%Y%m%d'))) from  task_execution  where begin_timestamp>'$day' and park_id in ('shanghai_auto_expo') group by year(begin_timestamp),week(begin_timestamp,1);"|python avg.py > c 
mysql -uaw_monitor -hszjjh-webserver.szjjh.autowise.ai -p123Qwe aw_monitor_system -e "select week(begin_timestamp,1),sum(timestampdiff(MINUTE,begin_timestamp,end_timestamp))/60 as innovation_duration, count(distinct(vehicle_id))  ,count(distinct(date_format(begin_timestamp,'%Y%m%d'))) from  task_execution  where begin_timestamp>'$day' and park_id in ('shanghai_innovation_port') group by year(begin_timestamp),week(begin_timestamp,1);" |python avg.py> d 
mysql -uaw_monitor -hszjjh-webserver.szjjh.autowise.ai -p123Qwe aw_monitor_system -e "select week(begin_timestamp,1),sum(timestampdiff(MINUTE,begin_timestamp,end_timestamp))/60 as boschung_duration, count(distinct(vehicle_id))  ,count(distinct(date_format(begin_timestamp,'%Y%m%d'))) from  task_execution  where begin_timestamp>'$day' and park_id in ('boschung_factory') group by year(begin_timestamp),week(begin_timestamp,1);" |python avg.py >  e
mysql -uaw_monitor -hszjjh-webserver.szjjh.autowise.ai -p123Qwe aw_monitor_system -e "select week(begin_timestamp,1),sum(timestampdiff(MINUTE,begin_timestamp,end_timestamp))/60 as walmart_duration, count(distinct(vehicle_id))   ,count(distinct(date_format(begin_timestamp,'%Y%m%d'))) from  task_execution  where begin_timestamp>'$day' and park_id in ('pheonix_walmart') group by year(begin_timestamp),week(begin_timestamp,1);" |python avg.py >  f
mysql -uaw_monitor -hszjjh-webserver.szjjh.autowise.ai -p123Qwe aw_monitor_system -e "select week(begin_timestamp,1),sum(timestampdiff(MINUTE,begin_timestamp,end_timestamp))/60 as guangzhou_duration, count(distinct(vehicle_id))  ,count(distinct(date_format(begin_timestamp,'%Y%m%d'))) from  task_execution  where begin_timestamp>'$day' and park_id in ('guangzhou_longhu','guangzhou_longhu_all','guangzhou_longhu_park') group by year(begin_timestamp),week(begin_timestamp,1);"|python avg.py >  g
mysql -uaw_monitor -hszjjh-webserver.szjjh.autowise.ai -p123Qwe aw_monitor_system -e "select week(begin_timestamp,1),sum(timestampdiff(MINUTE,begin_timestamp,end_timestamp))/60 as anting_duration, count(distinct(vehicle_id))  ,count(distinct(date_format(begin_timestamp,'%Y%m%d'))) from  task_execution  where begin_timestamp>'$day' and park_id in ('shanghai_anting_newtown') group by year(begin_timestamp),week(begin_timestamp,1);" |python avg.py >  h
mysql -uaw_monitor -hszjjh-webserver.szjjh.autowise.ai -p123Qwe aw_monitor_system -e "select week(begin_timestamp,1),sum(timestampdiff(MINUTE,begin_timestamp,end_timestamp))/60 as songjiang_duration, count(distinct(vehicle_id)) ,count(distinct(date_format(begin_timestamp,'%Y%m%d'))) from  task_execution  where begin_timestamp>'$day' and park_id in ('hanghai_songjiang_test','shanghai_songjiang_xinfeng','shanghai_tuspark') group by year(begin_timestamp),week(begin_timestamp,1);"|python avg.py >  i
mysql -uaw_monitor -hszjjh-webserver.szjjh.autowise.ai -p123Qwe aw_monitor_system -e "select week(begin_timestamp,1),sum(timestampdiff(MINUTE,begin_timestamp,end_timestamp))/60 as suzhou_duration, count(distinct(vehicle_id))  ,count(distinct(date_format(begin_timestamp,'%Y%m%d'))) from  task_execution  where begin_timestamp>'$day' and park_id in ('suzhou_station_square','suzhou_xiangcheng_all','suzhou_xiangcheng_demo','suzhou_demo_park') group by year(begin_timestamp),week(begin_timestamp,1);" |python avg.py> j 



python union.py a b c d e f g h i j |sort > result.duration_avg
