/aw/planning/aw_planning/itinerary/park_id : !!str boschung_factory
/aw/planning/aw_planning/itinerary/route_id : 9
/aw/planning/aw_planning/itinerary/tasks :

  #s20-s27
  - task_type :   !!str map
    start_east :    !!float 341215.31
    start_north:    !!float 5189354.525
    end_east :    !!float 341193.04
    end_north:    !!float 5189346.8125
    stop_check :  !!bool false
    max_velo  :   !!float 1.0
    execute_mode: !!int 2
    use_rel_ref:  !!bool false

  #s26-s20
  - task_type :   !!str map
    start_east :    !!float 341178.09
    start_north:    !!float 5189358.9125
    end_east :    !!float 341203.74
    end_north:    !!float 5189364.4125
    stop_check :  !!bool false
    max_velo  :   !!float 1.0
    execute_mode: !!int 2
    use_rel_ref:  !!bool false

/aw/planning/aw_planning/itinerary/task_index : !!int 0
/aw/planning/aw_planning/itinerary/repeated : !!bool true
/aw/planning/aw_planning/itinerary/repeat_start_index : !!int 0
